/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-11-22 02:50:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>社員登録画面</title>\n");
      out.write("<style>\n");
      out.write(".form-input {\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-table td {\n");
      out.write("	padding: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-table label {\n");
      out.write("	text-align: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-button {\n");
      out.write("	margin-top: 10px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<h1>社員登録画面</h1>\n");
      out.write("	<form action=\"ShainInsertComplete\" method=\"post\">\n");
      out.write("		<table class=\"form-table\">\n");
      out.write("			<tr>\n");
      out.write("				<td><label for=\"id\">ID:</label></td>\n");
      out.write("				<td><input type=\"text\" id=\"id\" name=\"id\" class=\"form-input\"\n");
      out.write("					pattern=\"\\d{3}\" required title=\"IDは3桁の数字で入力してください\"></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td><label for=\"name\">名前:</label></td>\n");
      out.write("				<td><input type=\"text\" id=\"name\" name=\"name\" class=\"form-input\"\n");
      out.write("					required></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td><label for=\"sei\">姓:</label></td>\n");
      out.write("				<td><select id=\"sei\" name=\"sei\" class=\"form-input\" required>\n");
      out.write("						<option value=\"\">選択してください</option>\n");
      out.write("						<option value=\"男\">男</option>\n");
      out.write("						<option value=\"女\">女</option>\n");
      out.write("				</select></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td><label for=\"nen\">年:</label></td>\n");
      out.write("				<td><select id=\"nen\" name=\"nen\" class=\"form-input\" required>\n");
      out.write("						<option value=\"\">選択してください</option>\n");
      out.write("						");

						for (int year = 2001; year <= 2024; year++) {
						
      out.write("\n");
      out.write("						<option value=\"");
      out.print(year);
      out.write('"');
      out.write('>');
      out.print(year);
      out.write("</option>\n");
      out.write("						");

						}
						
      out.write("\n");
      out.write("				</select></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td><label for=\"address\">住所:</label></td>\n");
      out.write("				<td><input type=\"text\" id=\"address\" name=\"address\"\n");
      out.write("					class=\"form-input\" required></td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("		<button type=\"submit\" class=\"form-button\">登録</button>\n");
      out.write("	</form>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
